 ################################################################### 
 # WARNING: this module is deprecated.                             # 
 # Please use CondCore.CondDB.CondDB_cfi.py                        # 
 ################################################################### 
# Conditions read from  CMS_CONDITIONS  via FrontierProd 
Seed initiated to 123456789
DEBUG 2017-05-08 12:51:37,267: 	 Executing command: 'submit'
DEBUG 2017-05-08 12:51:37,267: 	 Found CRAB cache file /afs/cern.ch/user/k/kjpena/.crab3
DEBUG 2017-05-08 12:51:37,272: 	 Checking credentials
DEBUG 2017-05-08 12:51:37,272: 	 Found proxy file /tmp/x509up_u81022
DEBUG 2017-05-08 12:51:37,272: 	 Getting proxy life time left
DEBUG 2017-05-08 12:51:37,785: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -timeleft
 output : 81292

 error: 
 retcode : 0
DEBUG 2017-05-08 12:51:38,295: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -actimeleft
 output : 81291

 error: 
 retcode : 0
DEBUG 2017-05-08 12:51:38,295: 	 Proxy valid for 22:34:52 hours
INFO 2017-05-08 12:51:38,295: 	 Will use CRAB configuration file crab_ZJ_ct14.py
DEBUG 2017-05-08 12:51:38,295: 	 Loading CRAB configuration file.
DEBUG 2017-05-08 12:51:38,301: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2017-05-08 12:51:38,492: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA

 error: 
 retcode : 0
DEBUG 2017-05-08 12:51:38,492: 	 Checking credentials
DEBUG 2017-05-08 12:51:38,493: 	 Found proxy file /tmp/x509up_u81022
DEBUG 2017-05-08 12:51:38,493: 	 Getting proxy life time left
DEBUG 2017-05-08 12:51:39,002: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -timeleft
 output : 81291

 error: 
 retcode : 0
DEBUG 2017-05-08 12:51:39,506: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -actimeleft
 output : 81290

 error: 
 retcode : 0
DEBUG 2017-05-08 12:51:39,506: 	 Proxy valid for 22:34:51 hours
DEBUG 2017-05-08 12:51:40,110: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u81022 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2017-05-08 12:51:40,439: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
DEBUG 2017-05-08 12:51:40,546: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA

 error: 
 retcode : 0
DEBUG 2017-05-08 12:51:40,546: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2017-05-08 12:51:40,546: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA_cmsweb.cern.ch for credential name
DEBUG 2017-05-08 12:51:40,751: 	 Executing : 
 command : myproxy-info -l 5c807b6c2de98292a7dc3f52d71970fa53af4385 -s myproxy.cern.ch
 output : username: 5c807b6c2de98292a7dc3f52d71970fa53af4385
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
  timeleft: 653:26:57  (27.2 days)

 error: 
 retcode : 0
DEBUG 2017-05-08 12:51:40,752: 	 Myproxy is valid: 2352417
DEBUG 2017-05-08 12:51:40,752: 	 Command use: submit
DEBUG 2017-05-08 12:51:40,752: 	 Options use: ['crab_ZJ_ct14.py']
DEBUG 2017-05-08 12:51:41,073: 	 CRABClient version: 3.3.1705.patch1
DEBUG 2017-05-08 12:51:41,073: 	 Instance is prod
DEBUG 2017-05-08 12:51:41,073: 	 Server base url is cmsweb.cern.ch
DEBUG 2017-05-08 12:51:41,073: 	 Command url /crabserver/prod/workflow
DEBUG 2017-05-08 12:51:41,073: 	 Started submission
DEBUG 2017-05-08 12:51:41,073: 	 Working on /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/test/macros/grid/crab_ZJ_ct14
DEBUG 2017-05-08 12:51:41,458: 	 Loading required information from the environment
DEBUG 2017-05-08 12:51:41,458: 	 Found CMSSW_8_0_8_patch1 for slc6_amd64_gcc530 with base /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1
DEBUG 2017-05-08 12:51:41,458: 	 Loading required information from the environment
DEBUG 2017-05-08 12:51:41,458: 	 Found CMSSW_8_0_8_patch1 for slc6_amd64_gcc530 with base /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1
DEBUG 2017-05-08 12:51:41,472: 	 UNIQUE NAME: tarUUID a48b9afd-e3fa-4579-8730-c8f83fd8bc59 
DEBUG 2017-05-08 12:51:41,472: 	 self.config: from WMCore.Configuration import Configuration
config = Configuration()
config.section_('General')
config.General.transferOutputs = True
config.General.workArea = 'grid'
config.General.requestName = 'ZJ_ct14'
config.section_('JobType')
config.JobType.psetName = '/afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/UserCode/VptGenAnalysis/test/runGENFromLHEandAnalysis_cfg.py'
config.JobType.pluginName = 'Analysis'
config.JobType.outputFiles = ['ZJ_ct14.root', 'ZJ_ct14.w0.yoda', 'ZJ_ct14.w1.yoda', 'ZJ_ct14.w2.yoda', 'ZJ_ct14.w3.yoda', 'ZJ_ct14.w4.yoda', 'ZJ_ct14.w5.yoda', 'ZJ_ct14.w6.yoda', 'ZJ_ct14.w7.yoda', 'ZJ_ct14.w8.yoda', 'ZJ_ct14.w9.yoda', 'ZJ_ct14.w10.yoda', 'ZJ_ct14.w11.yoda', 'ZJ_ct14.w12.yoda', 'ZJ_ct14.w13.yoda', 'ZJ_ct14.w14.yoda', 'ZJ_ct14.w15.yoda', 'ZJ_ct14.w16.yoda', 'ZJ_ct14.w17.yoda', 'ZJ_ct14.w18.yoda', 'ZJ_ct14.w19.yoda', 'ZJ_ct14.w20.yoda', 'ZJ_ct14.w21.yoda', 'ZJ_ct14.w22.yoda', 'ZJ_ct14.w23.yoda', 'ZJ_ct14.w24.yoda', 'ZJ_ct14.w25.yoda', 'ZJ_ct14.w26.yoda', 'ZJ_ct14.w27.yoda', 'ZJ_ct14.w28.yoda', 'ZJ_ct14.w29.yoda', 'ZJ_ct14.w30.yoda', 'ZJ_ct14.w31.yoda', 'ZJ_ct14.w32.yoda', 'ZJ_ct14.w33.yoda', 'ZJ_ct14.w34.yoda', 'ZJ_ct14.w35.yoda', 'ZJ_ct14.w36.yoda', 'ZJ_ct14.w37.yoda', 'ZJ_ct14.w38.yoda', 'ZJ_ct14.w39.yoda', 'ZJ_ct14.w40.yoda', 'ZJ_ct14.w41.yoda', 'ZJ_ct14.w42.yoda', 'ZJ_ct14.w43.yoda', 'ZJ_ct14.w44.yoda', 'ZJ_ct14.w45.yoda', 'ZJ_ct14.w46.yoda', 'ZJ_ct14.w47.yoda', 'ZJ_ct14.w48.yoda', 'ZJ_ct14.w49.yoda', 'ZJ_ct14.w50.yoda', 'ZJ_ct14.w51.yoda', 'ZJ_ct14.w52.yoda', 'ZJ_ct14.w53.yoda', 'ZJ_ct14.w54.yoda', 'ZJ_ct14.w55.yoda', 'ZJ_ct14.w56.yoda', 'ZJ_ct14.w57.yoda', 'ZJ_ct14.w58.yoda', 'ZJ_ct14.w59.yoda', 'ZJ_ct14.w60.yoda', 'ZJ_ct14.w61.yoda', 'ZJ_ct14.w62.yoda', 'ZJ_ct14.w63.yoda', 'ZJ_ct14.w64.yoda', 'ZJ_ct14.w65.yoda', 'ZJ_ct14.w66.yoda', 'ZJ_ct14.w67.yoda', 'ZJ_ct14.w68.yoda', 'ZJ_ct14.w69.yoda', 'ZJ_ct14.w70.yoda', 'ZJ_ct14.w71.yoda', 'ZJ_ct14.w72.yoda', 'ZJ_ct14.w73.yoda', 'ZJ_ct14.w74.yoda', 'ZJ_ct14.w75.yoda', 'ZJ_ct14.w76.yoda', 'ZJ_ct14.w77.yoda', 'ZJ_ct14.w78.yoda', 'ZJ_ct14.w79.yoda', 'ZJ_ct14.w80.yoda', 'ZJ_ct14.w81.yoda', 'ZJ_ct14.w82.yoda', 'ZJ_ct14.w83.yoda', 'ZJ_ct14.w84.yoda', 'ZJ_ct14.w85.yoda', 'ZJ_ct14.w86.yoda', 'ZJ_ct14.w87.yoda', 'ZJ_ct14.w88.yoda', 'ZJ_ct14.w89.yoda', 'ZJ_ct14.w90.yoda', 'ZJ_ct14.w91.yoda', 'ZJ_ct14.w92.yoda', 'ZJ_ct14.w93.yoda', 'ZJ_ct14.w94.yoda', 'ZJ_ct14.w95.yoda', 'ZJ_ct14.w96.yoda', 'ZJ_ct14.w97.yoda', 'ZJ_ct14.w98.yoda', 'ZJ_ct14.w99.yoda', 'ZJ_ct14.w100.yoda', 'ZJ_ct14.w101.yoda', 'ZJ_ct14.w102.yoda', 'ZJ_ct14.w103.yoda', 'ZJ_ct14.w104.yoda', 'ZJ_ct14.w105.yoda', 'ZJ_ct14.w106.yoda', 'ZJ_ct14.w107.yoda', 'ZJ_ct14.w108.yoda', 'ZJ_ct14.w109.yoda', 'ZJ_ct14.w110.yoda', 'ZJ_ct14.w111.yoda', 'ZJ_ct14.w112.yoda', 'ZJ_ct14.w113.yoda', 'ZJ_ct14.w114.yoda', 'ZJ_ct14.w115.yoda', 'ZJ_ct14.w116.yoda', 'ZJ_ct14.w117.yoda', 'ZJ_ct14.w118.yoda', 'ZJ_ct14.w119.yoda', 'ZJ_ct14.w120.yoda']
config.JobType.pyCfgParams = ['output=ZJ_ct14', 'ueTune=CUEP8M2T4', 'photos=True', 'nFinal=2', 'doRivetScan=True', 'usePoolSource=True']
config.JobType.disableAutomaticOutputCollection = True
config.section_('Data')
config.Data.inputDataset = '/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE'
config.Data.totalUnits = 10000
config.Data.unitsPerJob = 1000
config.Data.ignoreLocality = False
config.Data.inputDBS = 'global'
config.Data.splitting = 'EventAwareLumiBased'
config.Data.outLFNDirBase = '/store/group/phys_smp/Wmass/kjpena/ZJ_ct14'
config.Data.publication = False
config.section_('Site')
config.Site.storageSite = 'T2_CH_CERN'

DEBUG 2017-05-08 12:51:41,472: 	 self.config.JobType.psetName: /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/UserCode/VptGenAnalysis/test/runGENFromLHEandAnalysis_cfg.py
INFO 2017-05-08 12:51:41,472: 	 Importing CMSSW configuration /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/UserCode/VptGenAnalysis/test/runGENFromLHEandAnalysis_cfg.py
DEBUG 2017-05-08 12:51:41,473: 	 Additional parameters for the CMSSW configuration are: ['output=ZJ_ct14', 'ueTune=CUEP8M2T4', 'photos=True', 'nFinal=2', 'doRivetScan=True', 'usePoolSource=True']
INFO 2017-05-08 12:51:43,276: 	 Finished importing CMSSW configuration /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/UserCode/VptGenAnalysis/test/runGENFromLHEandAnalysis_cfg.py
DEBUG 2017-05-08 12:51:43,276: 	 Writing CMSSW configuration to /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/test/macros/grid/crab_ZJ_ct14/inputs/PSet.py
DEBUG 2017-05-08 12:51:43,860: 	 The following EDM output files will be collected: []
DEBUG 2017-05-08 12:51:43,860: 	 The following TFile output files will be collected: ['ZJ_ct14.root']
DEBUG 2017-05-08 12:51:43,860: 	 The following user output files will be collected: ['ZJ_ct14.w0.yoda', 'ZJ_ct14.w1.yoda', 'ZJ_ct14.w2.yoda', 'ZJ_ct14.w3.yoda', 'ZJ_ct14.w4.yoda', 'ZJ_ct14.w5.yoda', 'ZJ_ct14.w6.yoda', 'ZJ_ct14.w7.yoda', 'ZJ_ct14.w8.yoda', 'ZJ_ct14.w9.yoda', 'ZJ_ct14.w10.yoda', 'ZJ_ct14.w11.yoda', 'ZJ_ct14.w12.yoda', 'ZJ_ct14.w13.yoda', 'ZJ_ct14.w14.yoda', 'ZJ_ct14.w15.yoda', 'ZJ_ct14.w16.yoda', 'ZJ_ct14.w17.yoda', 'ZJ_ct14.w18.yoda', 'ZJ_ct14.w19.yoda', 'ZJ_ct14.w20.yoda', 'ZJ_ct14.w21.yoda', 'ZJ_ct14.w22.yoda', 'ZJ_ct14.w23.yoda', 'ZJ_ct14.w24.yoda', 'ZJ_ct14.w25.yoda', 'ZJ_ct14.w26.yoda', 'ZJ_ct14.w27.yoda', 'ZJ_ct14.w28.yoda', 'ZJ_ct14.w29.yoda', 'ZJ_ct14.w30.yoda', 'ZJ_ct14.w31.yoda', 'ZJ_ct14.w32.yoda', 'ZJ_ct14.w33.yoda', 'ZJ_ct14.w34.yoda', 'ZJ_ct14.w35.yoda', 'ZJ_ct14.w36.yoda', 'ZJ_ct14.w37.yoda', 'ZJ_ct14.w38.yoda', 'ZJ_ct14.w39.yoda', 'ZJ_ct14.w40.yoda', 'ZJ_ct14.w41.yoda', 'ZJ_ct14.w42.yoda', 'ZJ_ct14.w43.yoda', 'ZJ_ct14.w44.yoda', 'ZJ_ct14.w45.yoda', 'ZJ_ct14.w46.yoda', 'ZJ_ct14.w47.yoda', 'ZJ_ct14.w48.yoda', 'ZJ_ct14.w49.yoda', 'ZJ_ct14.w50.yoda', 'ZJ_ct14.w51.yoda', 'ZJ_ct14.w52.yoda', 'ZJ_ct14.w53.yoda', 'ZJ_ct14.w54.yoda', 'ZJ_ct14.w55.yoda', 'ZJ_ct14.w56.yoda', 'ZJ_ct14.w57.yoda', 'ZJ_ct14.w58.yoda', 'ZJ_ct14.w59.yoda', 'ZJ_ct14.w60.yoda', 'ZJ_ct14.w61.yoda', 'ZJ_ct14.w62.yoda', 'ZJ_ct14.w63.yoda', 'ZJ_ct14.w64.yoda', 'ZJ_ct14.w65.yoda', 'ZJ_ct14.w66.yoda', 'ZJ_ct14.w67.yoda', 'ZJ_ct14.w68.yoda', 'ZJ_ct14.w69.yoda', 'ZJ_ct14.w70.yoda', 'ZJ_ct14.w71.yoda', 'ZJ_ct14.w72.yoda', 'ZJ_ct14.w73.yoda', 'ZJ_ct14.w74.yoda', 'ZJ_ct14.w75.yoda', 'ZJ_ct14.w76.yoda', 'ZJ_ct14.w77.yoda', 'ZJ_ct14.w78.yoda', 'ZJ_ct14.w79.yoda', 'ZJ_ct14.w80.yoda', 'ZJ_ct14.w81.yoda', 'ZJ_ct14.w82.yoda', 'ZJ_ct14.w83.yoda', 'ZJ_ct14.w84.yoda', 'ZJ_ct14.w85.yoda', 'ZJ_ct14.w86.yoda', 'ZJ_ct14.w87.yoda', 'ZJ_ct14.w88.yoda', 'ZJ_ct14.w89.yoda', 'ZJ_ct14.w90.yoda', 'ZJ_ct14.w91.yoda', 'ZJ_ct14.w92.yoda', 'ZJ_ct14.w93.yoda', 'ZJ_ct14.w94.yoda', 'ZJ_ct14.w95.yoda', 'ZJ_ct14.w96.yoda', 'ZJ_ct14.w97.yoda', 'ZJ_ct14.w98.yoda', 'ZJ_ct14.w99.yoda', 'ZJ_ct14.w100.yoda', 'ZJ_ct14.w101.yoda', 'ZJ_ct14.w102.yoda', 'ZJ_ct14.w103.yoda', 'ZJ_ct14.w104.yoda', 'ZJ_ct14.w105.yoda', 'ZJ_ct14.w106.yoda', 'ZJ_ct14.w107.yoda', 'ZJ_ct14.w108.yoda', 'ZJ_ct14.w109.yoda', 'ZJ_ct14.w110.yoda', 'ZJ_ct14.w111.yoda', 'ZJ_ct14.w112.yoda', 'ZJ_ct14.w113.yoda', 'ZJ_ct14.w114.yoda', 'ZJ_ct14.w115.yoda', 'ZJ_ct14.w116.yoda', 'ZJ_ct14.w117.yoda', 'ZJ_ct14.w118.yoda', 'ZJ_ct14.w119.yoda', 'ZJ_ct14.w120.yoda']
DEBUG 2017-05-08 12:51:43,860: 	 Loading required information from the environment
DEBUG 2017-05-08 12:51:43,860: 	 Found CMSSW_8_0_8_patch1 for slc6_amd64_gcc530 with base /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1
DEBUG 2017-05-08 12:51:43,860: 	 Making tarball in /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/test/macros/grid/crab_ZJ_ct14/inputs/a48b9afd-e3fa-4579-8730-c8f83fd8bc59default.tgz
DEBUG 2017-05-08 12:51:43,865: 	 Checking directory /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/lib
DEBUG 2017-05-08 12:51:43,865: 	 Adding directory /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/lib to tarball
DEBUG 2017-05-08 12:51:44,045: 	 Checking directory /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/biglib
DEBUG 2017-05-08 12:51:44,045: 	 Adding directory /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/biglib to tarball
DEBUG 2017-05-08 12:51:44,046: 	 Checking directory /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/module
DEBUG 2017-05-08 12:51:44,048: 	 Adding data directory /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/GeneratorInterface/RivetInterface/data to tarball
DEBUG 2017-05-08 12:51:44,129: 	 Adding data directory /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/GeneratorInterface/RivetInterface/interface to tarball
DEBUG 2017-05-08 12:51:44,135: 	 Adding data directory /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/UserCode/RivetAnalysis/data to tarball
DEBUG 2017-05-08 12:51:44,363: 	 Uploading archive /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/test/macros/grid/crab_ZJ_ct14/inputs/a48b9afd-e3fa-4579-8730-c8f83fd8bc59default.tgz (0.567383.1 MB) to the CRAB cache. Using URI https://cmsweb.cern.ch/crabcache
DEBUG 2017-05-08 12:51:44,866: 	 Loading required information from the environment
DEBUG 2017-05-08 12:51:44,866: 	 Found CMSSW_8_0_8_patch1 for slc6_amd64_gcc530 with base /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1
DEBUG 2017-05-08 12:51:44,866: 	 Making tarball in /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/test/macros/grid/crab_ZJ_ct14/inputs/debugFiles.tgz
DEBUG 2017-05-08 12:51:44,869: 	 Uploading archive /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/test/macros/grid/crab_ZJ_ct14/inputs/debugFiles.tgz (3 KB) to the CRAB cache. Using URI https://cmsweb.cern.ch/crabcache
DEBUG 2017-05-08 12:51:45,197: 	 Result uploading input files: ad516605c131d2940b68d2b797be5ada115f72a5d27ef929e566d924f6fb5e50.tar.gz 
INFO 2017-05-08 12:51:45,197: 	 Sending the request to the server
DEBUG 2017-05-08 12:51:45,198: 	 Submitting {'maxjobruntime': 1250, 'extrajdl': [], 'ignorelocality': 0, 'savelogsflag': 0, 'useparent': 0, 'asyncdest': 'T2_CH_CERN', 'algoargs': 1000, 'cachefilename': 'ad516605c131d2940b68d2b797be5ada115f72a5d27ef929e566d924f6fb5e50.tar.gz', 'numcores': 1, 'addoutputfiles': ['ZJ_ct14.w0.yoda', 'ZJ_ct14.w1.yoda', 'ZJ_ct14.w2.yoda', 'ZJ_ct14.w3.yoda', 'ZJ_ct14.w4.yoda', 'ZJ_ct14.w5.yoda', 'ZJ_ct14.w6.yoda', 'ZJ_ct14.w7.yoda', 'ZJ_ct14.w8.yoda', 'ZJ_ct14.w9.yoda', 'ZJ_ct14.w10.yoda', 'ZJ_ct14.w11.yoda', 'ZJ_ct14.w12.yoda', 'ZJ_ct14.w13.yoda', 'ZJ_ct14.w14.yoda', 'ZJ_ct14.w15.yoda', 'ZJ_ct14.w16.yoda', 'ZJ_ct14.w17.yoda', 'ZJ_ct14.w18.yoda', 'ZJ_ct14.w19.yoda', 'ZJ_ct14.w20.yoda', 'ZJ_ct14.w21.yoda', 'ZJ_ct14.w22.yoda', 'ZJ_ct14.w23.yoda', 'ZJ_ct14.w24.yoda', 'ZJ_ct14.w25.yoda', 'ZJ_ct14.w26.yoda', 'ZJ_ct14.w27.yoda', 'ZJ_ct14.w28.yoda', 'ZJ_ct14.w29.yoda', 'ZJ_ct14.w30.yoda', 'ZJ_ct14.w31.yoda', 'ZJ_ct14.w32.yoda', 'ZJ_ct14.w33.yoda', 'ZJ_ct14.w34.yoda', 'ZJ_ct14.w35.yoda', 'ZJ_ct14.w36.yoda', 'ZJ_ct14.w37.yoda', 'ZJ_ct14.w38.yoda', 'ZJ_ct14.w39.yoda', 'ZJ_ct14.w40.yoda', 'ZJ_ct14.w41.yoda', 'ZJ_ct14.w42.yoda', 'ZJ_ct14.w43.yoda', 'ZJ_ct14.w44.yoda', 'ZJ_ct14.w45.yoda', 'ZJ_ct14.w46.yoda', 'ZJ_ct14.w47.yoda', 'ZJ_ct14.w48.yoda', 'ZJ_ct14.w49.yoda', 'ZJ_ct14.w50.yoda', 'ZJ_ct14.w51.yoda', 'ZJ_ct14.w52.yoda', 'ZJ_ct14.w53.yoda', 'ZJ_ct14.w54.yoda', 'ZJ_ct14.w55.yoda', 'ZJ_ct14.w56.yoda', 'ZJ_ct14.w57.yoda', 'ZJ_ct14.w58.yoda', 'ZJ_ct14.w59.yoda', 'ZJ_ct14.w60.yoda', 'ZJ_ct14.w61.yoda', 'ZJ_ct14.w62.yoda', 'ZJ_ct14.w63.yoda', 'ZJ_ct14.w64.yoda', 'ZJ_ct14.w65.yoda', 'ZJ_ct14.w66.yoda', 'ZJ_ct14.w67.yoda', 'ZJ_ct14.w68.yoda', 'ZJ_ct14.w69.yoda', 'ZJ_ct14.w70.yoda', 'ZJ_ct14.w71.yoda', 'ZJ_ct14.w72.yoda', 'ZJ_ct14.w73.yoda', 'ZJ_ct14.w74.yoda', 'ZJ_ct14.w75.yoda', 'ZJ_ct14.w76.yoda', 'ZJ_ct14.w77.yoda', 'ZJ_ct14.w78.yoda', 'ZJ_ct14.w79.yoda', 'ZJ_ct14.w80.yoda', 'ZJ_ct14.w81.yoda', 'ZJ_ct14.w82.yoda', 'ZJ_ct14.w83.yoda', 'ZJ_ct14.w84.yoda', 'ZJ_ct14.w85.yoda', 'ZJ_ct14.w86.yoda', 'ZJ_ct14.w87.yoda', 'ZJ_ct14.w88.yoda', 'ZJ_ct14.w89.yoda', 'ZJ_ct14.w90.yoda', 'ZJ_ct14.w91.yoda', 'ZJ_ct14.w92.yoda', 'ZJ_ct14.w93.yoda', 'ZJ_ct14.w94.yoda', 'ZJ_ct14.w95.yoda', 'ZJ_ct14.w96.yoda', 'ZJ_ct14.w97.yoda', 'ZJ_ct14.w98.yoda', 'ZJ_ct14.w99.yoda', 'ZJ_ct14.w100.yoda', 'ZJ_ct14.w101.yoda', 'ZJ_ct14.w102.yoda', 'ZJ_ct14.w103.yoda', 'ZJ_ct14.w104.yoda', 'ZJ_ct14.w105.yoda', 'ZJ_ct14.w106.yoda', 'ZJ_ct14.w107.yoda', 'ZJ_ct14.w108.yoda', 'ZJ_ct14.w109.yoda', 'ZJ_ct14.w110.yoda', 'ZJ_ct14.w111.yoda', 'ZJ_ct14.w112.yoda', 'ZJ_ct14.w113.yoda', 'ZJ_ct14.w114.yoda', 'ZJ_ct14.w115.yoda', 'ZJ_ct14.w116.yoda', 'ZJ_ct14.w117.yoda', 'ZJ_ct14.w118.yoda', 'ZJ_ct14.w119.yoda', 'ZJ_ct14.w120.yoda'], 'generator': 'pythia', 'maxmemory': 2000, 'publishdbsurl': 'https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter', 'priority': 10, 'jobsw': 'CMSSW_8_0_8_patch1', 'edmoutfiles': [], 'userfiles': [], 'primarydataset': '', 'inputdata': '/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE', 'lfn': '/store/group/phys_smp/Wmass/kjpena/ZJ_ct14', 'dryrun': 0, 'workflow': 'crab_ZJ_ct14', 'cacheurl': u'https://cmsweb.cern.ch/crabcache', 'nonprodsw': 0, 'tfileoutfiles': ['ZJ_ct14.root'], 'oneEventMode': 0, 'debugfilename': 'fffb3e61d8dc3cb1157866a95b8896a3e10646acecd7436096c89065bd05070f.tar.gz', 'saveoutput': 1, 'publication': 0, 'jobarch': 'slc6_amd64_gcc530', 'totalunits': 10000, 'splitalgo': 'EventAwareLumiBased', 'ignoreglobalblacklist': 0, 'nonvaliddata': 0, 'dbsurl': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader', 'publishgroupname': 0, 'jobtype': 'Analysis', 'publishname2': ''} 
DEBUG 2017-05-08 12:51:45,198: 	 Encoded submit request: maxjobruntime=1250&ignorelocality=0&savelogsflag=0&useparent=0&asyncdest=T2_CH_CERN&algoargs=1000&cachefilename=ad516605c131d2940b68d2b797be5ada115f72a5d27ef929e566d924f6fb5e50.tar.gz&numcores=1&generator=pythia&maxmemory=2000&publishdbsurl=https%3A%2F%2Fcmsweb.cern.ch%2Fdbs%2Fprod%2Fphys03%2FDBSWriter&priority=10&jobsw=CMSSW_8_0_8_patch1&primarydataset=&inputdata=%2FZJ_ZToMuMu_powheg_minlo_8TeV_CT14%2FRunIIWinter15wmLHE-MCRUN2_71_V1-v1%2FLHE&lfn=%2Fstore%2Fgroup%2Fphys_smp%2FWmass%2Fkjpena%2FZJ_ct14&dryrun=0&workflow=crab_ZJ_ct14&cacheurl=https%3A%2F%2Fcmsweb.cern.ch%2Fcrabcache&nonprodsw=0&oneEventMode=0&debugfilename=fffb3e61d8dc3cb1157866a95b8896a3e10646acecd7436096c89065bd05070f.tar.gz&saveoutput=1&publication=0&jobarch=slc6_amd64_gcc530&totalunits=10000&splitalgo=EventAwareLumiBased&ignoreglobalblacklist=0&nonvaliddata=0&dbsurl=https%3A%2F%2Fcmsweb.cern.ch%2Fdbs%2Fprod%2Fglobal%2FDBSReader&publishgroupname=0&jobtype=Analysis&publishname2=&addoutputfiles=ZJ_ct14.w0.yoda&addoutputfiles=ZJ_ct14.w1.yoda&addoutputfiles=ZJ_ct14.w2.yoda&addoutputfiles=ZJ_ct14.w3.yoda&addoutputfiles=ZJ_ct14.w4.yoda&addoutputfiles=ZJ_ct14.w5.yoda&addoutputfiles=ZJ_ct14.w6.yoda&addoutputfiles=ZJ_ct14.w7.yoda&addoutputfiles=ZJ_ct14.w8.yoda&addoutputfiles=ZJ_ct14.w9.yoda&addoutputfiles=ZJ_ct14.w10.yoda&addoutputfiles=ZJ_ct14.w11.yoda&addoutputfiles=ZJ_ct14.w12.yoda&addoutputfiles=ZJ_ct14.w13.yoda&addoutputfiles=ZJ_ct14.w14.yoda&addoutputfiles=ZJ_ct14.w15.yoda&addoutputfiles=ZJ_ct14.w16.yoda&addoutputfiles=ZJ_ct14.w17.yoda&addoutputfiles=ZJ_ct14.w18.yoda&addoutputfiles=ZJ_ct14.w19.yoda&addoutputfiles=ZJ_ct14.w20.yoda&addoutputfiles=ZJ_ct14.w21.yoda&addoutputfiles=ZJ_ct14.w22.yoda&addoutputfiles=ZJ_ct14.w23.yoda&addoutputfiles=ZJ_ct14.w24.yoda&addoutputfiles=ZJ_ct14.w25.yoda&addoutputfiles=ZJ_ct14.w26.yoda&addoutputfiles=ZJ_ct14.w27.yoda&addoutputfiles=ZJ_ct14.w28.yoda&addoutputfiles=ZJ_ct14.w29.yoda&addoutputfiles=ZJ_ct14.w30.yoda&addoutputfiles=ZJ_ct14.w31.yoda&addoutputfiles=ZJ_ct14.w32.yoda&addoutputfiles=ZJ_ct14.w33.yoda&addoutputfiles=ZJ_ct14.w34.yoda&addoutputfiles=ZJ_ct14.w35.yoda&addoutputfiles=ZJ_ct14.w36.yoda&addoutputfiles=ZJ_ct14.w37.yoda&addoutputfiles=ZJ_ct14.w38.yoda&addoutputfiles=ZJ_ct14.w39.yoda&addoutputfiles=ZJ_ct14.w40.yoda&addoutputfiles=ZJ_ct14.w41.yoda&addoutputfiles=ZJ_ct14.w42.yoda&addoutputfiles=ZJ_ct14.w43.yoda&addoutputfiles=ZJ_ct14.w44.yoda&addoutputfiles=ZJ_ct14.w45.yoda&addoutputfiles=ZJ_ct14.w46.yoda&addoutputfiles=ZJ_ct14.w47.yoda&addoutputfiles=ZJ_ct14.w48.yoda&addoutputfiles=ZJ_ct14.w49.yoda&addoutputfiles=ZJ_ct14.w50.yoda&addoutputfiles=ZJ_ct14.w51.yoda&addoutputfiles=ZJ_ct14.w52.yoda&addoutputfiles=ZJ_ct14.w53.yoda&addoutputfiles=ZJ_ct14.w54.yoda&addoutputfiles=ZJ_ct14.w55.yoda&addoutputfiles=ZJ_ct14.w56.yoda&addoutputfiles=ZJ_ct14.w57.yoda&addoutputfiles=ZJ_ct14.w58.yoda&addoutputfiles=ZJ_ct14.w59.yoda&addoutputfiles=ZJ_ct14.w60.yoda&addoutputfiles=ZJ_ct14.w61.yoda&addoutputfiles=ZJ_ct14.w62.yoda&addoutputfiles=ZJ_ct14.w63.yoda&addoutputfiles=ZJ_ct14.w64.yoda&addoutputfiles=ZJ_ct14.w65.yoda&addoutputfiles=ZJ_ct14.w66.yoda&addoutputfiles=ZJ_ct14.w67.yoda&addoutputfiles=ZJ_ct14.w68.yoda&addoutputfiles=ZJ_ct14.w69.yoda&addoutputfiles=ZJ_ct14.w70.yoda&addoutputfiles=ZJ_ct14.w71.yoda&addoutputfiles=ZJ_ct14.w72.yoda&addoutputfiles=ZJ_ct14.w73.yoda&addoutputfiles=ZJ_ct14.w74.yoda&addoutputfiles=ZJ_ct14.w75.yoda&addoutputfiles=ZJ_ct14.w76.yoda&addoutputfiles=ZJ_ct14.w77.yoda&addoutputfiles=ZJ_ct14.w78.yoda&addoutputfiles=ZJ_ct14.w79.yoda&addoutputfiles=ZJ_ct14.w80.yoda&addoutputfiles=ZJ_ct14.w81.yoda&addoutputfiles=ZJ_ct14.w82.yoda&addoutputfiles=ZJ_ct14.w83.yoda&addoutputfiles=ZJ_ct14.w84.yoda&addoutputfiles=ZJ_ct14.w85.yoda&addoutputfiles=ZJ_ct14.w86.yoda&addoutputfiles=ZJ_ct14.w87.yoda&addoutputfiles=ZJ_ct14.w88.yoda&addoutputfiles=ZJ_ct14.w89.yoda&addoutputfiles=ZJ_ct14.w90.yoda&addoutputfiles=ZJ_ct14.w91.yoda&addoutputfiles=ZJ_ct14.w92.yoda&addoutputfiles=ZJ_ct14.w93.yoda&addoutputfiles=ZJ_ct14.w94.yoda&addoutputfiles=ZJ_ct14.w95.yoda&addoutputfiles=ZJ_ct14.w96.yoda&addoutputfiles=ZJ_ct14.w97.yoda&addoutputfiles=ZJ_ct14.w98.yoda&addoutputfiles=ZJ_ct14.w99.yoda&addoutputfiles=ZJ_ct14.w100.yoda&addoutputfiles=ZJ_ct14.w101.yoda&addoutputfiles=ZJ_ct14.w102.yoda&addoutputfiles=ZJ_ct14.w103.yoda&addoutputfiles=ZJ_ct14.w104.yoda&addoutputfiles=ZJ_ct14.w105.yoda&addoutputfiles=ZJ_ct14.w106.yoda&addoutputfiles=ZJ_ct14.w107.yoda&addoutputfiles=ZJ_ct14.w108.yoda&addoutputfiles=ZJ_ct14.w109.yoda&addoutputfiles=ZJ_ct14.w110.yoda&addoutputfiles=ZJ_ct14.w111.yoda&addoutputfiles=ZJ_ct14.w112.yoda&addoutputfiles=ZJ_ct14.w113.yoda&addoutputfiles=ZJ_ct14.w114.yoda&addoutputfiles=ZJ_ct14.w115.yoda&addoutputfiles=ZJ_ct14.w116.yoda&addoutputfiles=ZJ_ct14.w117.yoda&addoutputfiles=ZJ_ct14.w118.yoda&addoutputfiles=ZJ_ct14.w119.yoda&addoutputfiles=ZJ_ct14.w120.yoda&tfileoutfiles=ZJ_ct14.root
DEBUG 2017-05-08 12:51:45,771: 	 Result: {u'result': [{u'RequestName': u'170508_105145:kjpena_crab_ZJ_ct14'}]}
INFO 2017-05-08 12:51:45,773: 	 Success: Your task has been delivered to the CRAB3 server.
INFO 2017-05-08 12:51:45,773: 	 Task name: 170508_105145:kjpena_crab_ZJ_ct14
INFO 2017-05-08 12:51:45,774: 	 Please use 'crab status' to check how the submission process proceeds.
DEBUG 2017-05-08 12:51:45,774: 	 About to return
INFO 2017-05-08 12:51:45,776: 	 Log file is /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/test/macros/grid/crab_ZJ_ct14/crab.log
DEBUG 2017-05-09 19:04:00,900: 	 Executing command: 'report'
DEBUG 2017-05-09 19:04:00,901: 	 Found CRAB cache file /afs/cern.ch/user/k/kjpena/.crab3
DEBUG 2017-05-09 19:04:00,907: 	 Checking credentials
DEBUG 2017-05-09 19:04:00,907: 	 Proxy file /tmp/x509up_u81022 not found
DEBUG 2017-05-09 19:04:00,907: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2017-05-09 19:04:11,901: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 0
DEBUG 2017-05-09 19:04:12,717: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -timeleft
 output : 86398

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:13,449: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -actimeleft
 output : 86397

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:14,166: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u81022 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:14,166: 	 Proxy created.
DEBUG 2017-05-09 19:04:14,323: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:14,323: 	 Checking credentials
DEBUG 2017-05-09 19:04:14,324: 	 Found proxy file /tmp/x509up_u81022
DEBUG 2017-05-09 19:04:14,324: 	 Getting proxy life time left
DEBUG 2017-05-09 19:04:15,147: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -timeleft
 output : 86395

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:15,856: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -actimeleft
 output : 86395

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:15,857: 	 Proxy valid for 23:59:55 hours
DEBUG 2017-05-09 19:04:16,312: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
DEBUG 2017-05-09 19:04:16,425: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:16,425: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2017-05-09 19:04:16,426: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA_cmsweb.cern.ch for credential name
DEBUG 2017-05-09 19:04:16,731: 	 Executing : 
 command : myproxy-info -l 5c807b6c2de98292a7dc3f52d71970fa53af4385 -s myproxy.cern.ch
 output : username: 5c807b6c2de98292a7dc3f52d71970fa53af4385
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
  timeleft: 623:14:21  (26.0 days)

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:16,733: 	 Myproxy is valid: 2243661
DEBUG 2017-05-09 19:04:16,733: 	 Command use: report
DEBUG 2017-05-09 19:04:16,733: 	 Options use: ['-d', 'test/macros/grid/crab_ZJ_ct14/']
DEBUG 2017-05-09 19:04:17,178: 	 CRABClient version: 3.3.1705.patch3
DEBUG 2017-05-09 19:04:17,178: 	 Instance is prod
DEBUG 2017-05-09 19:04:17,178: 	 Server base url is cmsweb.cern.ch
DEBUG 2017-05-09 19:04:17,178: 	 Command url /crabserver/prod/workflow
DEBUG 2017-05-09 19:04:17,179: 	 Looking up report for task 170508_105145:kjpena_crab_ZJ_ct14
DEBUG 2017-05-09 19:04:17,580: 	 Result: {u'result': [{u'runsAndLumis': {}, u'taskDBInfo': {u'inputDataset': u'/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE', u'userWebDirURL': u'http://vocms0122.cern.ch/mon/cms447/170508_105145:kjpena_crab_ZJ_ct14', u'publication': False, u'outputDatasets': []}}]}
INFO 2017-05-09 19:04:17,580: 	 Running crab status2 first to fetch necessary information.
DEBUG 2017-05-09 19:04:17,580: 	 Executing command: 'status'
DEBUG 2017-05-09 19:04:17,580: 	 Found CRAB cache file /afs/cern.ch/user/k/kjpena/.crab3
DEBUG 2017-05-09 19:04:17,593: 	 Checking credentials
DEBUG 2017-05-09 19:04:17,594: 	 Found proxy file /tmp/x509up_u81022
DEBUG 2017-05-09 19:04:17,595: 	 Getting proxy life time left
DEBUG 2017-05-09 19:04:18,401: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -timeleft
 output : 86392

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:19,111: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -actimeleft
 output : 86391

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:19,112: 	 Proxy valid for 23:59:52 hours
DEBUG 2017-05-09 19:04:19,228: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:19,228: 	 Checking credentials
DEBUG 2017-05-09 19:04:19,228: 	 Found proxy file /tmp/x509up_u81022
DEBUG 2017-05-09 19:04:19,228: 	 Getting proxy life time left
DEBUG 2017-05-09 19:04:20,048: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -timeleft
 output : 86391

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:21,277: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -actimeleft
 output : 86389

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:21,277: 	 Proxy valid for 23:59:51 hours
DEBUG 2017-05-09 19:04:21,662: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
DEBUG 2017-05-09 19:04:21,771: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:21,772: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2017-05-09 19:04:21,772: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA_cmsweb.cern.ch for credential name
DEBUG 2017-05-09 19:04:21,976: 	 Executing : 
 command : myproxy-info -l 5c807b6c2de98292a7dc3f52d71970fa53af4385 -s myproxy.cern.ch
 output : username: 5c807b6c2de98292a7dc3f52d71970fa53af4385
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
  timeleft: 623:14:16  (26.0 days)

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:21,977: 	 Myproxy is valid: 2243656
DEBUG 2017-05-09 19:04:21,977: 	 Command use: status
DEBUG 2017-05-09 19:04:21,977: 	 Options use: []
DEBUG 2017-05-09 19:04:22,351: 	 CRABClient version: 3.3.1705.patch3
DEBUG 2017-05-09 19:04:22,351: 	 Instance is prod
DEBUG 2017-05-09 19:04:22,351: 	 Server base url is cmsweb.cern.ch
DEBUG 2017-05-09 19:04:22,351: 	 Command url /crabserver/prod/workflow
DEBUG 2017-05-09 19:04:22,726: 	 Got information from server oracle database: {u'result': [u'170508_105145:kjpena_crab_ZJ_ct14', u'None', u'SUBMITTED', u'2017-05-08 10:51:45.757999', u'None', u'2017-05-08 10:52:54.137742', u'None', u'CMSSW_8_0_8_patch1', u'slc6_amd64_gcc530', u'/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE', u'[]', u'[]', u'EventAwareLumiBased', u"{'splitOnRun': False, 'events_per_job': 1000, 'halt_job_on_file_boundaries': False, 'runs': [], 'lumis': []}", u'10000', u'ad516605c131d2940b68d2b797be5ada115f72a5d27ef929e566d924f6fb5e50.tar.gz', u'https://cmsweb.cern.ch/crabcache', u'kjpena', u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA', u'cms', u'None', u'None', u'crab_ZJ_ct14-00000000000000000000000000000000', u'T2_CH_CERN', u'https://cmsweb.cern.ch/dbs/prod/global/DBSReader', u'https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter', u'F', u'Analysis', u'{}', u'[]', u'F', u'vocms052', u'[]', u'1250', u'1', u'2000', u'10', u'None', u'http://vocms0122.cern.ch/mon/cms447/170508_105145:kjpena_crab_ZJ_ct14', u'None', u'None', u'[]', u'[]', u'[]', u'pythia', u"['ZJ_ct14.w0.yoda', 'ZJ_ct14.w1.yoda', 'ZJ_ct14.w2.yoda', 'ZJ_ct14.w3.yoda', 'ZJ_ct14.w4.yoda', 'ZJ_ct14.w5.yoda', 'ZJ_ct14.w6.yoda', 'ZJ_ct14.w7.yoda', 'ZJ_ct14.w8.yoda', 'ZJ_ct14.w9.yoda', 'ZJ_ct14.w10.yoda', 'ZJ_ct14.w11.yoda', 'ZJ_ct14.w12.yoda', 'ZJ_ct14.w13.yoda', 'ZJ_ct14.w14.yoda', 'ZJ_ct14.w15.yoda', 'ZJ_ct14.w16.yoda', 'ZJ_ct14.w17.yoda', 'ZJ_ct14.w18.yoda', 'ZJ_ct14.w19.yoda', 'ZJ_ct14.w20.yoda', 'ZJ_ct14.w21.yoda', 'ZJ_ct14.w22.yoda', 'ZJ_ct14.w23.yoda', 'ZJ_ct14.w24.yoda', 'ZJ_ct14.w25.yoda', 'ZJ_ct14.w26.yoda', 'ZJ_ct14.w27.yoda', 'ZJ_ct14.w28.yoda', 'ZJ_ct14.w29.yoda', 'ZJ_ct14.w30.yoda', 'ZJ_ct14.w31.yoda', 'ZJ_ct14.w32.yoda', 'ZJ_ct14.w33.yoda', 'ZJ_ct14.w34.yoda', 'ZJ_ct14.w35.yoda', 'ZJ_ct14.w36.yoda', 'ZJ_ct14.w37.yoda', 'ZJ_ct14.w38.yoda', 'ZJ_ct14.w39.yoda', 'ZJ_ct14.w40.yoda', 'ZJ_ct14.w41.yoda', 'ZJ_ct14.w42.yoda', 'ZJ_ct14.w43.yoda', 'ZJ_ct14.w44.yoda', 'ZJ_ct14.w45.yoda', 'ZJ_ct14.w46.yoda', 'ZJ_ct14.w47.yoda', 'ZJ_ct14.w48.yoda', 'ZJ_ct14.w49.yoda', 'ZJ_ct14.w50.yoda', 'ZJ_ct14.w51.yoda', 'ZJ_ct14.w52.yoda', 'ZJ_ct14.w53.yoda', 'ZJ_ct14.w54.yoda', 'ZJ_ct14.w55.yoda', 'ZJ_ct14.w56.yoda', 'ZJ_ct14.w57.yoda', 'ZJ_ct14.w58.yoda', 'ZJ_ct14.w59.yoda', 'ZJ_ct14.w60.yoda', 'ZJ_ct14.w61.yoda', 'ZJ_ct14.w62.yoda', 'ZJ_ct14.w63.yoda', 'ZJ_ct14.w64.yoda', 'ZJ_ct14.w65.yoda', 'ZJ_ct14.w66.yoda', 'ZJ_ct14.w67.yoda', 'ZJ_ct14.w68.yoda', 'ZJ_ct14.w69.yoda', 'ZJ_ct14.w70.yoda', 'ZJ_ct14.w71.yoda', 'ZJ_ct14.w72.yoda', 'ZJ_ct14.w73.yoda', 'ZJ_ct14.w74.yoda', 'ZJ_ct14.w75.yoda', 'ZJ_ct14.w76.yoda', 'ZJ_ct14.w77.yoda', 'ZJ_ct14.w78.yoda', 'ZJ_ct14.w79.yoda', 'ZJ_ct14.w80.yoda', 'ZJ_ct14.w81.yoda', 'ZJ_ct14.w82.yoda', 'ZJ_ct14.w83.yoda', 'ZJ_ct14.w84.yoda', 'ZJ_ct14.w85.yoda', 'ZJ_ct14.w86.yoda', 'ZJ_ct14.w87.yoda', 'ZJ_ct14.w88.yoda', 'ZJ_ct14.w89.yoda', 'ZJ_ct14.w90.yoda', 'ZJ_ct14.w91.yoda', 'ZJ_ct14.w92.yoda', 'ZJ_ct14.w93.yoda', 'ZJ_ct14.w94.yoda', 'ZJ_ct14.w95.yoda', 'ZJ_ct14.w96.yoda', 'ZJ_ct14.w97.yoda', 'ZJ_ct14.w98.yoda', 'ZJ_ct14.w99.yoda', 'ZJ_ct14.w100.yoda', 'ZJ_ct14.w101.yoda', 'ZJ_ct14.w102.yoda', 'ZJ_ct14.w103.yoda', 'ZJ_ct14.w104.yoda', 'ZJ_ct14.w105.yoda', 'ZJ_ct14.w106.yoda', 'ZJ_ct14.w107.yoda', 'ZJ_ct14.w108.yoda', 'ZJ_ct14.w109.yoda', 'ZJ_ct14.w110.yoda', 'ZJ_ct14.w111.yoda', 'ZJ_ct14.w112.yoda', 'ZJ_ct14.w113.yoda', 'ZJ_ct14.w114.yoda', 'ZJ_ct14.w115.yoda', 'ZJ_ct14.w116.yoda', 'ZJ_ct14.w117.yoda', 'ZJ_ct14.w118.yoda', 'ZJ_ct14.w119.yoda', 'ZJ_ct14.w120.yoda']", u"['ZJ_ct14.root']", u'[]', u'https://cmsweb.cern.ch/crabserver/prod', u'None', u'0', u'cmsgwms-collector-global.cern.ch:9620,cmssrv221.fnal.gov:9620', u'crab3@vocms0122.cern.ch', u'F', u'[]', u'T', u'/store/group/phys_smp/Wmass/kjpena/ZJ_ct14', u'F', u'None', u'F', u'F', u'F', u'None', u'ZJ_ZToMuMu_powheg_minlo_8TeV_CT14', u'filetransfers', u'SUBMIT', u'13830161', u'fffb3e61d8dc3cb1157866a95b8896a3e10646acecd7436096c89065bd05070f.tar.gz', u'188.184.92.85', u'F', u'None'], u'desc': {u'columns': [u'tm_taskname', u'panda_jobset_id', u'tm_task_status', u'tm_start_time', u'tm_start_injection', u'tm_end_injection', u'tm_task_failure', u'tm_job_sw', u'tm_job_arch', u'tm_input_dataset', u'tm_site_whitelist', u'tm_site_blacklist', u'tm_split_algo', u'tm_split_args', u'tm_totalunits', u'tm_user_sandbox', u'tm_cache_url', u'tm_username', u'tm_user_dn', u'tm_user_vo', u'tm_user_role', u'tm_user_group', u'tm_publish_name', u'tm_asyncdest', u'tm_dbs_url', u'tm_publish_dbs_url', u'tm_publication', u'tm_job_type', u'tm_arguments', u'panda_resubmitted_jobs', u'tm_save_logs', u'tw_name', u'tm_user_infiles', u'tm_maxjobruntime', u'tm_numcores', u'tm_maxmemory', u'tm_priority', u'tm_output_dataset', u'tm_user_webdir', u'tm_activity', u'tm_scriptexe', u'tm_scriptargs', u'tm_extrajdl', u'tm_task_warnings', u'tm_generator', u'tm_outfiles', u'tm_tfile_outfiles', u'tm_edm_outfiles', u'tm_asourl', u'tm_events_per_lumi', u'tm_use_parent', u'tm_collector', u'tm_schedd', u'tm_dry_run', u'tm_user_files', u'tm_transfer_outputs', u'tm_output_lfn', u'tm_ignore_locality', u'tm_fail_limit', u'tm_one_event_mode', u'tm_publish_groupname', u'tm_nonvalid_input_dataset', u'tm_secondary_input_dataset', u'tm_primary_dataset', u'tm_asodb', u'tm_task_command', u'clusterid', u'tm_debug_files', u'tm_submitter_ip_addr', u'tm_ignore_global_blacklist', u'tm_last_publication']}}
INFO 2017-05-09 19:04:22,727: 	 CRAB project directory:		/afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/test/macros/grid/crab_ZJ_ct14
INFO 2017-05-09 19:04:22,727: 	 Task name:			170508_105145:kjpena_crab_ZJ_ct14
INFO 2017-05-09 19:04:22,727: 	 Grid scheduler:			crab3@vocms0122.cern.ch
INFO 2017-05-09 19:04:22,727: 	 Status on the CRAB server:	SUBMITTED
INFO 2017-05-09 19:04:22,727: 	 Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/170508_105145%3Akjpena_crab_ZJ_ct14
INFO 2017-05-09 19:04:22,727: 	 Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=kjpena&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=170508_105145%3Akjpena_crab_ZJ_ct14
DEBUG 2017-05-09 19:04:22,727: 	 The CRAB server submitted your task to the Grid scheduler (cluster ID: 13830161)
DEBUG 2017-05-09 19:04:22,727: 	 Webdir is located at http://vocms0122.cern.ch/mon/cms447/170508_105145:kjpena_crab_ZJ_ct14
DEBUG 2017-05-09 19:04:23,194: 	 Proxied webdir is located at https://cmsweb.cern.ch/scheddmon/0122/cms447/170508_105145:kjpena_crab_ZJ_ct14
DEBUG 2017-05-09 19:04:23,194: 	 Retrieving 'status_cache' file from https://cmsweb.cern.ch/scheddmon/0122/cms447/170508_105145:kjpena_crab_ZJ_ct14/status_cache
DEBUG 2017-05-09 19:04:23,636: 	 Got information from status cache file: {'11': {'Retries': 2, 'WallDurations': [10.0, 1209.0, 9.0, 1415.0, 9.0, 1207.0], 'StartTimes': [1494241329.0, 1494242858.0, 1494244527.0], 'SubmitTimes': [1494240767.0, 1494242607.0, 1494244402.0], 'JobIds': ['13830172.0', '13830788.0', '13831871.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494242538.0, 1494244273.0, 1494245734.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [291844, 295064, 293592], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '10': {'Retries': 2, 'WallDurations': [10.0, 1207.0, 10.0, 1208.0, 9.0, 1232.0], 'StartTimes': [1494240958.0, 1494242373.0, 1494244251.0], 'SubmitTimes': [1494240766.0, 1494242233.0, 1494243708.0], 'JobIds': ['13830169.0', '13830754.0', '13831820.0'], 'EndTimes': [1494242165.0, 1494243581.0, 1494245483.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [287280, 24608, 292212], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'TotalUserCpuTimeHistory': [3, 3, 4], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '1': {'Retries': 2, 'WallDurations': [9.0, 1207.0, 1974.0, 8.0, 7289.0], 'StartTimes': [1494241796.0, 1494243164.0, 1494245648.0], 'SubmitTimes': [1494240766.0, 1494243072.0, 1494245268.0], 'JobIds': ['13830168.0', '13830850.0', '13832320.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494243003.0, 1494245138.0, 1494252937.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [293596, 294312, 154908], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '3': {'Retries': 2, 'WallDurations': [9.0, 1208.0, 9.0, 1955.0, 9.0, 1207.0], 'StartTimes': [1494241632.0, 1494243165.0, 1494245503.0], 'SubmitTimes': [1494240766.0, 1494242911.0, 1494245247.0], 'JobIds': ['13830166.0', '13830830.0', '13832319.0'], 'EndTimes': [1494242840.0, 1494245120.0, 1494246710.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [292212, 295432, 292328], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'TotalUserCpuTimeHistory': [3, 3, 3], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '2': {'Retries': 2, 'WallDurations': [9.0, 1207.0, 9.0, 1209.0, 9.0, 1207.0], 'StartTimes': [1494241941.0, 1494243302.0, 1494244801.0], 'SubmitTimes': [1494240767.0, 1494243217.0, 1494244639.0], 'JobIds': ['13830173.0', '13830861.0', '13831901.0'], 'EndTimes': [1494243148.0, 1494244511.0, 1494246008.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [294388, 294616, 294664], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'TotalUserCpuTimeHistory': [3, 3, 3], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '5': {'Retries': 2, 'WallDurations': [9.0, 1207.0, 8.0, 1207.0, 9.0, 1335.0], 'StartTimes': [1494242117.0, 1494243597.0, 1494245137.0], 'SubmitTimes': [1494240767.0, 1494243395.0, 1494244930.0], 'JobIds': ['13830174.0', '13831434.0', '13831926.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494243324.0, 1494244804.0, 1494246472.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [293900, 294752, 294088], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '4': {'Retries': 2, 'WallDurations': [9.0, 1207.0, 9.0, 2152.0, 9.0, 7210.0], 'StartTimes': [1494241631.0, 1494243020.0, 1494245721.0], 'SubmitTimes': [1494240766.0, 1494242905.0, 1494245299.0], 'JobIds': ['13830167.0', '13830824.0', '13832324.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494242838.0, 1494245172.0, 1494252931.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [295860, 296944, 294324], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '7': {'Retries': 2, 'WallDurations': [8.0, 1206.0, 9.0, 2178.0, 10.0, 1207.0], 'StartTimes': [1494241154.0, 1494242666.0, 1494245092.0], 'SubmitTimes': [1494240766.0, 1494242429.0, 1494244971.0], 'JobIds': ['13830164.0', '13830775.0', '13831932.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494242360.0, 1494244844.0, 1494246299.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [293752, 293632, 283472], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '6': {'Retries': 2, 'WallDurations': [9.0, 1206.0, 2586.0, 9.0, 1211.0], 'StartTimes': [1494241152.0, 1494242554.0, 1494245370.0], 'SubmitTimes': [1494240766.0, 1494242424.0, 1494245268.0], 'JobIds': ['13830171.0', '13830774.0', '13832321.0'], 'EndTimes': [1494242358.0, 1494245140.0, 1494246581.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [294556, 294680, 24372], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'TotalUserCpuTimeHistory': [3, 3, 3], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '9': {'Retries': 2, 'WallDurations': [9.0, 1207.0, 9.0, 1896.0, 8.0, 1207.0], 'StartTimes': [1494240958.0, 1494242377.0, 1494244496.0], 'SubmitTimes': [1494240766.0, 1494242234.0, 1494244402.0], 'JobIds': ['13830165.0', '13830755.0', '13831870.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494242165.0, 1494244273.0, 1494245703.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [290644, 296940, 291824], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '8': {'Retries': 2, 'WallDurations': [10.0, 1207.0, 9.0, 1424.0, 8.0, 1207.0], 'StartTimes': [1494241154.0, 1494242851.0, 1494244632.0], 'SubmitTimes': [1494240766.0, 1494242429.0, 1494244407.0], 'JobIds': ['13830170.0', '13830776.0', '13831872.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494242361.0, 1494244275.0, 1494245839.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [293480, 294388, 294644], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}}
INFO 2017-05-09 19:04:23,637: 	 Status on the scheduler:	FAILED
INFO 2017-05-09 19:04:23,637: 	 
Jobs status:                    failed        100.0% (11/11)
INFO 2017-05-09 19:04:23,637: 	 
No publication information (publication has been disabled in the CRAB configuration file)
INFO 2017-05-09 19:04:23,637: 	 
Error Summary: (use crab status --verboseErrors for details about the errors)

11 jobs failed with exit code 8028

Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.
INFO 2017-05-09 19:04:25,107: 	 Error: Cannot get all the needed information for the report. Notice, if your task has been submitted more than 30 days ago, then everything has been cleaned.
INFO 2017-05-09 19:04:25,159: 	 Log file is /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/test/macros/grid/crab_ZJ_ct14/crab.log
DEBUG 2017-05-09 19:04:52,763: 	 Executing command: 'report'
DEBUG 2017-05-09 19:04:52,764: 	 Found CRAB cache file /afs/cern.ch/user/k/kjpena/.crab3
DEBUG 2017-05-09 19:04:52,773: 	 Checking credentials
DEBUG 2017-05-09 19:04:52,774: 	 Found proxy file /tmp/x509up_u81022
DEBUG 2017-05-09 19:04:52,774: 	 Getting proxy life time left
DEBUG 2017-05-09 19:04:53,780: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -timeleft
 output : 86357

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:54,593: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -actimeleft
 output : 86356

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:54,593: 	 Proxy valid for 23:59:17 hours
DEBUG 2017-05-09 19:04:54,900: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:54,900: 	 Checking credentials
DEBUG 2017-05-09 19:04:54,901: 	 Found proxy file /tmp/x509up_u81022
DEBUG 2017-05-09 19:04:54,901: 	 Getting proxy life time left
DEBUG 2017-05-09 19:04:55,830: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -timeleft
 output : 86355

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:56,538: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -actimeleft
 output : 86354

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:56,538: 	 Proxy valid for 23:59:15 hours
DEBUG 2017-05-09 19:04:56,908: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
DEBUG 2017-05-09 19:04:57,019: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:57,019: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2017-05-09 19:04:57,020: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA_cmsweb.cern.ch for credential name
DEBUG 2017-05-09 19:04:57,328: 	 Executing : 
 command : myproxy-info -l 5c807b6c2de98292a7dc3f52d71970fa53af4385 -s myproxy.cern.ch
 output : username: 5c807b6c2de98292a7dc3f52d71970fa53af4385
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
  timeleft: 623:13:40  (26.0 days)

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:57,329: 	 Myproxy is valid: 2243620
DEBUG 2017-05-09 19:04:57,329: 	 Command use: report
DEBUG 2017-05-09 19:04:57,329: 	 Options use: ['test/macros/grid/crab_ZJ_ct14/']
DEBUG 2017-05-09 19:04:57,825: 	 CRABClient version: 3.3.1705.patch3
DEBUG 2017-05-09 19:04:57,826: 	 Instance is prod
DEBUG 2017-05-09 19:04:57,826: 	 Server base url is cmsweb.cern.ch
DEBUG 2017-05-09 19:04:57,826: 	 Command url /crabserver/prod/workflow
DEBUG 2017-05-09 19:04:57,826: 	 Looking up report for task 170508_105145:kjpena_crab_ZJ_ct14
DEBUG 2017-05-09 19:04:58,266: 	 Result: {u'result': [{u'runsAndLumis': {}, u'taskDBInfo': {u'inputDataset': u'/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE', u'userWebDirURL': u'http://vocms0122.cern.ch/mon/cms447/170508_105145:kjpena_crab_ZJ_ct14', u'publication': False, u'outputDatasets': []}}]}
INFO 2017-05-09 19:04:58,266: 	 Running crab status2 first to fetch necessary information.
DEBUG 2017-05-09 19:04:58,266: 	 Executing command: 'status'
DEBUG 2017-05-09 19:04:58,267: 	 Found CRAB cache file /afs/cern.ch/user/k/kjpena/.crab3
DEBUG 2017-05-09 19:04:58,277: 	 Checking credentials
DEBUG 2017-05-09 19:04:58,277: 	 Found proxy file /tmp/x509up_u81022
DEBUG 2017-05-09 19:04:58,277: 	 Getting proxy life time left
DEBUG 2017-05-09 19:04:59,089: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -timeleft
 output : 86351

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:59,961: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -actimeleft
 output : 86351

 error: 
 retcode : 0
DEBUG 2017-05-09 19:04:59,961: 	 Proxy valid for 23:59:11 hours
DEBUG 2017-05-09 19:05:00,093: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA

 error: 
 retcode : 0
DEBUG 2017-05-09 19:05:00,094: 	 Checking credentials
DEBUG 2017-05-09 19:05:00,094: 	 Found proxy file /tmp/x509up_u81022
DEBUG 2017-05-09 19:05:00,094: 	 Getting proxy life time left
DEBUG 2017-05-09 19:05:00,900: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -timeleft
 output : 86350

 error: 
 retcode : 0
DEBUG 2017-05-09 19:05:01,608: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81022 -actimeleft
 output : 86349

 error: 
 retcode : 0
DEBUG 2017-05-09 19:05:01,608: 	 Proxy valid for 23:59:10 hours
DEBUG 2017-05-09 19:05:02,000: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
DEBUG 2017-05-09 19:05:02,113: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA

 error: 
 retcode : 0
DEBUG 2017-05-09 19:05:02,113: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2017-05-09 19:05:02,113: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA_cmsweb.cern.ch for credential name
DEBUG 2017-05-09 19:05:02,317: 	 Executing : 
 command : myproxy-info -l 5c807b6c2de98292a7dc3f52d71970fa53af4385 -s myproxy.cern.ch
 output : username: 5c807b6c2de98292a7dc3f52d71970fa53af4385
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
  timeleft: 623:13:35  (26.0 days)

 error: 
 retcode : 0
DEBUG 2017-05-09 19:05:02,317: 	 Myproxy is valid: 2243615
DEBUG 2017-05-09 19:05:02,317: 	 Command use: status
DEBUG 2017-05-09 19:05:02,318: 	 Options use: []
DEBUG 2017-05-09 19:05:02,703: 	 CRABClient version: 3.3.1705.patch3
DEBUG 2017-05-09 19:05:02,703: 	 Instance is prod
DEBUG 2017-05-09 19:05:02,703: 	 Server base url is cmsweb.cern.ch
DEBUG 2017-05-09 19:05:02,703: 	 Command url /crabserver/prod/workflow
DEBUG 2017-05-09 19:05:03,217: 	 Got information from server oracle database: {u'result': [u'170508_105145:kjpena_crab_ZJ_ct14', u'None', u'SUBMITTED', u'2017-05-08 10:51:45.757999', u'None', u'2017-05-08 10:52:54.137742', u'None', u'CMSSW_8_0_8_patch1', u'slc6_amd64_gcc530', u'/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE', u'[]', u'[]', u'EventAwareLumiBased', u"{'splitOnRun': False, 'events_per_job': 1000, 'halt_job_on_file_boundaries': False, 'runs': [], 'lumis': []}", u'10000', u'ad516605c131d2940b68d2b797be5ada115f72a5d27ef929e566d924f6fb5e50.tar.gz', u'https://cmsweb.cern.ch/crabcache', u'kjpena', u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=kjpena/CN=748777/CN=Karla PENA', u'cms', u'None', u'None', u'crab_ZJ_ct14-00000000000000000000000000000000', u'T2_CH_CERN', u'https://cmsweb.cern.ch/dbs/prod/global/DBSReader', u'https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter', u'F', u'Analysis', u'{}', u'[]', u'F', u'vocms052', u'[]', u'1250', u'1', u'2000', u'10', u'None', u'http://vocms0122.cern.ch/mon/cms447/170508_105145:kjpena_crab_ZJ_ct14', u'None', u'None', u'[]', u'[]', u'[]', u'pythia', u"['ZJ_ct14.w0.yoda', 'ZJ_ct14.w1.yoda', 'ZJ_ct14.w2.yoda', 'ZJ_ct14.w3.yoda', 'ZJ_ct14.w4.yoda', 'ZJ_ct14.w5.yoda', 'ZJ_ct14.w6.yoda', 'ZJ_ct14.w7.yoda', 'ZJ_ct14.w8.yoda', 'ZJ_ct14.w9.yoda', 'ZJ_ct14.w10.yoda', 'ZJ_ct14.w11.yoda', 'ZJ_ct14.w12.yoda', 'ZJ_ct14.w13.yoda', 'ZJ_ct14.w14.yoda', 'ZJ_ct14.w15.yoda', 'ZJ_ct14.w16.yoda', 'ZJ_ct14.w17.yoda', 'ZJ_ct14.w18.yoda', 'ZJ_ct14.w19.yoda', 'ZJ_ct14.w20.yoda', 'ZJ_ct14.w21.yoda', 'ZJ_ct14.w22.yoda', 'ZJ_ct14.w23.yoda', 'ZJ_ct14.w24.yoda', 'ZJ_ct14.w25.yoda', 'ZJ_ct14.w26.yoda', 'ZJ_ct14.w27.yoda', 'ZJ_ct14.w28.yoda', 'ZJ_ct14.w29.yoda', 'ZJ_ct14.w30.yoda', 'ZJ_ct14.w31.yoda', 'ZJ_ct14.w32.yoda', 'ZJ_ct14.w33.yoda', 'ZJ_ct14.w34.yoda', 'ZJ_ct14.w35.yoda', 'ZJ_ct14.w36.yoda', 'ZJ_ct14.w37.yoda', 'ZJ_ct14.w38.yoda', 'ZJ_ct14.w39.yoda', 'ZJ_ct14.w40.yoda', 'ZJ_ct14.w41.yoda', 'ZJ_ct14.w42.yoda', 'ZJ_ct14.w43.yoda', 'ZJ_ct14.w44.yoda', 'ZJ_ct14.w45.yoda', 'ZJ_ct14.w46.yoda', 'ZJ_ct14.w47.yoda', 'ZJ_ct14.w48.yoda', 'ZJ_ct14.w49.yoda', 'ZJ_ct14.w50.yoda', 'ZJ_ct14.w51.yoda', 'ZJ_ct14.w52.yoda', 'ZJ_ct14.w53.yoda', 'ZJ_ct14.w54.yoda', 'ZJ_ct14.w55.yoda', 'ZJ_ct14.w56.yoda', 'ZJ_ct14.w57.yoda', 'ZJ_ct14.w58.yoda', 'ZJ_ct14.w59.yoda', 'ZJ_ct14.w60.yoda', 'ZJ_ct14.w61.yoda', 'ZJ_ct14.w62.yoda', 'ZJ_ct14.w63.yoda', 'ZJ_ct14.w64.yoda', 'ZJ_ct14.w65.yoda', 'ZJ_ct14.w66.yoda', 'ZJ_ct14.w67.yoda', 'ZJ_ct14.w68.yoda', 'ZJ_ct14.w69.yoda', 'ZJ_ct14.w70.yoda', 'ZJ_ct14.w71.yoda', 'ZJ_ct14.w72.yoda', 'ZJ_ct14.w73.yoda', 'ZJ_ct14.w74.yoda', 'ZJ_ct14.w75.yoda', 'ZJ_ct14.w76.yoda', 'ZJ_ct14.w77.yoda', 'ZJ_ct14.w78.yoda', 'ZJ_ct14.w79.yoda', 'ZJ_ct14.w80.yoda', 'ZJ_ct14.w81.yoda', 'ZJ_ct14.w82.yoda', 'ZJ_ct14.w83.yoda', 'ZJ_ct14.w84.yoda', 'ZJ_ct14.w85.yoda', 'ZJ_ct14.w86.yoda', 'ZJ_ct14.w87.yoda', 'ZJ_ct14.w88.yoda', 'ZJ_ct14.w89.yoda', 'ZJ_ct14.w90.yoda', 'ZJ_ct14.w91.yoda', 'ZJ_ct14.w92.yoda', 'ZJ_ct14.w93.yoda', 'ZJ_ct14.w94.yoda', 'ZJ_ct14.w95.yoda', 'ZJ_ct14.w96.yoda', 'ZJ_ct14.w97.yoda', 'ZJ_ct14.w98.yoda', 'ZJ_ct14.w99.yoda', 'ZJ_ct14.w100.yoda', 'ZJ_ct14.w101.yoda', 'ZJ_ct14.w102.yoda', 'ZJ_ct14.w103.yoda', 'ZJ_ct14.w104.yoda', 'ZJ_ct14.w105.yoda', 'ZJ_ct14.w106.yoda', 'ZJ_ct14.w107.yoda', 'ZJ_ct14.w108.yoda', 'ZJ_ct14.w109.yoda', 'ZJ_ct14.w110.yoda', 'ZJ_ct14.w111.yoda', 'ZJ_ct14.w112.yoda', 'ZJ_ct14.w113.yoda', 'ZJ_ct14.w114.yoda', 'ZJ_ct14.w115.yoda', 'ZJ_ct14.w116.yoda', 'ZJ_ct14.w117.yoda', 'ZJ_ct14.w118.yoda', 'ZJ_ct14.w119.yoda', 'ZJ_ct14.w120.yoda']", u"['ZJ_ct14.root']", u'[]', u'https://cmsweb.cern.ch/crabserver/prod', u'None', u'0', u'cmsgwms-collector-global.cern.ch:9620,cmssrv221.fnal.gov:9620', u'crab3@vocms0122.cern.ch', u'F', u'[]', u'T', u'/store/group/phys_smp/Wmass/kjpena/ZJ_ct14', u'F', u'None', u'F', u'F', u'F', u'None', u'ZJ_ZToMuMu_powheg_minlo_8TeV_CT14', u'filetransfers', u'SUBMIT', u'13830161', u'fffb3e61d8dc3cb1157866a95b8896a3e10646acecd7436096c89065bd05070f.tar.gz', u'188.184.92.85', u'F', u'None'], u'desc': {u'columns': [u'tm_taskname', u'panda_jobset_id', u'tm_task_status', u'tm_start_time', u'tm_start_injection', u'tm_end_injection', u'tm_task_failure', u'tm_job_sw', u'tm_job_arch', u'tm_input_dataset', u'tm_site_whitelist', u'tm_site_blacklist', u'tm_split_algo', u'tm_split_args', u'tm_totalunits', u'tm_user_sandbox', u'tm_cache_url', u'tm_username', u'tm_user_dn', u'tm_user_vo', u'tm_user_role', u'tm_user_group', u'tm_publish_name', u'tm_asyncdest', u'tm_dbs_url', u'tm_publish_dbs_url', u'tm_publication', u'tm_job_type', u'tm_arguments', u'panda_resubmitted_jobs', u'tm_save_logs', u'tw_name', u'tm_user_infiles', u'tm_maxjobruntime', u'tm_numcores', u'tm_maxmemory', u'tm_priority', u'tm_output_dataset', u'tm_user_webdir', u'tm_activity', u'tm_scriptexe', u'tm_scriptargs', u'tm_extrajdl', u'tm_task_warnings', u'tm_generator', u'tm_outfiles', u'tm_tfile_outfiles', u'tm_edm_outfiles', u'tm_asourl', u'tm_events_per_lumi', u'tm_use_parent', u'tm_collector', u'tm_schedd', u'tm_dry_run', u'tm_user_files', u'tm_transfer_outputs', u'tm_output_lfn', u'tm_ignore_locality', u'tm_fail_limit', u'tm_one_event_mode', u'tm_publish_groupname', u'tm_nonvalid_input_dataset', u'tm_secondary_input_dataset', u'tm_primary_dataset', u'tm_asodb', u'tm_task_command', u'clusterid', u'tm_debug_files', u'tm_submitter_ip_addr', u'tm_ignore_global_blacklist', u'tm_last_publication']}}
INFO 2017-05-09 19:05:03,217: 	 CRAB project directory:		/afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/test/macros/grid/crab_ZJ_ct14
INFO 2017-05-09 19:05:03,217: 	 Task name:			170508_105145:kjpena_crab_ZJ_ct14
INFO 2017-05-09 19:05:03,217: 	 Grid scheduler:			crab3@vocms0122.cern.ch
INFO 2017-05-09 19:05:03,217: 	 Status on the CRAB server:	SUBMITTED
INFO 2017-05-09 19:05:03,217: 	 Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/170508_105145%3Akjpena_crab_ZJ_ct14
INFO 2017-05-09 19:05:03,217: 	 Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=kjpena&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=170508_105145%3Akjpena_crab_ZJ_ct14
DEBUG 2017-05-09 19:05:03,217: 	 The CRAB server submitted your task to the Grid scheduler (cluster ID: 13830161)
DEBUG 2017-05-09 19:05:03,217: 	 Webdir is located at http://vocms0122.cern.ch/mon/cms447/170508_105145:kjpena_crab_ZJ_ct14
DEBUG 2017-05-09 19:05:03,665: 	 Proxied webdir is located at https://cmsweb.cern.ch/scheddmon/0122/cms447/170508_105145:kjpena_crab_ZJ_ct14
DEBUG 2017-05-09 19:05:03,666: 	 Retrieving 'status_cache' file from https://cmsweb.cern.ch/scheddmon/0122/cms447/170508_105145:kjpena_crab_ZJ_ct14/status_cache
DEBUG 2017-05-09 19:05:04,051: 	 Got information from status cache file: {'11': {'Retries': 2, 'WallDurations': [10.0, 1209.0, 9.0, 1415.0, 9.0, 1207.0], 'StartTimes': [1494241329.0, 1494242858.0, 1494244527.0], 'SubmitTimes': [1494240767.0, 1494242607.0, 1494244402.0], 'JobIds': ['13830172.0', '13830788.0', '13831871.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494242538.0, 1494244273.0, 1494245734.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [291844, 295064, 293592], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '10': {'Retries': 2, 'WallDurations': [10.0, 1207.0, 10.0, 1208.0, 9.0, 1232.0], 'StartTimes': [1494240958.0, 1494242373.0, 1494244251.0], 'SubmitTimes': [1494240766.0, 1494242233.0, 1494243708.0], 'JobIds': ['13830169.0', '13830754.0', '13831820.0'], 'EndTimes': [1494242165.0, 1494243581.0, 1494245483.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [287280, 24608, 292212], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'TotalUserCpuTimeHistory': [3, 3, 4], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '1': {'Retries': 2, 'WallDurations': [9.0, 1207.0, 1974.0, 8.0, 7289.0], 'StartTimes': [1494241796.0, 1494243164.0, 1494245648.0], 'SubmitTimes': [1494240766.0, 1494243072.0, 1494245268.0], 'JobIds': ['13830168.0', '13830850.0', '13832320.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494243003.0, 1494245138.0, 1494252937.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [293596, 294312, 154908], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '3': {'Retries': 2, 'WallDurations': [9.0, 1208.0, 9.0, 1955.0, 9.0, 1207.0], 'StartTimes': [1494241632.0, 1494243165.0, 1494245503.0], 'SubmitTimes': [1494240766.0, 1494242911.0, 1494245247.0], 'JobIds': ['13830166.0', '13830830.0', '13832319.0'], 'EndTimes': [1494242840.0, 1494245120.0, 1494246710.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [292212, 295432, 292328], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'TotalUserCpuTimeHistory': [3, 3, 3], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '2': {'Retries': 2, 'WallDurations': [9.0, 1207.0, 9.0, 1209.0, 9.0, 1207.0], 'StartTimes': [1494241941.0, 1494243302.0, 1494244801.0], 'SubmitTimes': [1494240767.0, 1494243217.0, 1494244639.0], 'JobIds': ['13830173.0', '13830861.0', '13831901.0'], 'EndTimes': [1494243148.0, 1494244511.0, 1494246008.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [294388, 294616, 294664], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'TotalUserCpuTimeHistory': [3, 3, 3], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '5': {'Retries': 2, 'WallDurations': [9.0, 1207.0, 8.0, 1207.0, 9.0, 1335.0], 'StartTimes': [1494242117.0, 1494243597.0, 1494245137.0], 'SubmitTimes': [1494240767.0, 1494243395.0, 1494244930.0], 'JobIds': ['13830174.0', '13831434.0', '13831926.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494243324.0, 1494244804.0, 1494246472.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [293900, 294752, 294088], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '4': {'Retries': 2, 'WallDurations': [9.0, 1207.0, 9.0, 2152.0, 9.0, 7210.0], 'StartTimes': [1494241631.0, 1494243020.0, 1494245721.0], 'SubmitTimes': [1494240766.0, 1494242905.0, 1494245299.0], 'JobIds': ['13830167.0', '13830824.0', '13832324.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494242838.0, 1494245172.0, 1494252931.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [295860, 296944, 294324], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '7': {'Retries': 2, 'WallDurations': [8.0, 1206.0, 9.0, 2178.0, 10.0, 1207.0], 'StartTimes': [1494241154.0, 1494242666.0, 1494245092.0], 'SubmitTimes': [1494240766.0, 1494242429.0, 1494244971.0], 'JobIds': ['13830164.0', '13830775.0', '13831932.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494242360.0, 1494244844.0, 1494246299.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [293752, 293632, 283472], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '6': {'Retries': 2, 'WallDurations': [9.0, 1206.0, 2586.0, 9.0, 1211.0], 'StartTimes': [1494241152.0, 1494242554.0, 1494245370.0], 'SubmitTimes': [1494240766.0, 1494242424.0, 1494245268.0], 'JobIds': ['13830171.0', '13830774.0', '13832321.0'], 'EndTimes': [1494242358.0, 1494245140.0, 1494246581.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [294556, 294680, 24372], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'TotalUserCpuTimeHistory': [3, 3, 3], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '9': {'Retries': 2, 'WallDurations': [9.0, 1207.0, 9.0, 1896.0, 8.0, 1207.0], 'StartTimes': [1494240958.0, 1494242377.0, 1494244496.0], 'SubmitTimes': [1494240766.0, 1494242234.0, 1494244402.0], 'JobIds': ['13830165.0', '13830755.0', '13831870.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494242165.0, 1494244273.0, 1494245703.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [290644, 296940, 291824], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-redic.pi.infn.it,+1213llrxrd-redir.in2p3.fr,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd.ba.infn.it,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}, '8': {'Retries': 2, 'WallDurations': [10.0, 1207.0, 9.0, 1424.0, 8.0, 1207.0], 'StartTimes': [1494241154.0, 1494242851.0, 1494244632.0], 'SubmitTimes': [1494240766.0, 1494242429.0, 1494244407.0], 'JobIds': ['13830170.0', '13830776.0', '13831872.0'], 'TotalUserCpuTimeHistory': [3, 3, 3], 'EndTimes': [1494242361.0, 1494244275.0, 1494245839.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'failed', 'ResidentSetSize': [293480, 294388, 294644], 'Error': [8028, "CmsRunFailure\nCMSSW error message follows.\nFatal Exception\nAn exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094\n", {'type': 'Fatal Exception', 'details': "An exception of category 'FallbackFileOpenError' occurred while\n   [0] Constructing the EventProcessor\n   [1] Constructing input source of type PoolSource\n   [2] Calling RootFileSequenceBase::initTheFile()\n   [3] Calling StorageFactory::open()\n   [4] Calling XrdFile::open()\nException Message:\nFailed to open the file 'root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root'\n   Additional Info:\n      [a] XrdCl::File::Open(name='root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [b] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd.ba.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [c] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [d] Disabled source: cms-xrd-transit.cern.ch:1094\n      [e] Input file root://se01.grid.nchc.org.tw//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root could not be opened.\nFallback Input file root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root also could not be opened.\nOriginal exception info is above; fallback exception info is below.\n      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.\n' (errno=3011, code=400). No additional data servers were found.\n      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/mc/RunIIWinter15wmLHE/ZJ_ZToMuMu_powheg_minlo_8TeV_CT14/LHE/MCRUN2_71_V1-v1/110000/58B398B2-E3F5-E611-976A-001A649D5019.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,+1213xrootd-cms-redir-01.cr.cnaf.infn.it,+1213llrxrd-redir.in2p3.fr,+se01.grid.nchc.o.1213xrootd-redic.pi1213xrootd-cms-redir-01.cr.cnaf1213llrxrd-redir.in2p3.fr1213xrootd.ba.infn.it,\n      [h] Problematic data server: cms-xrd-transit.cern.ch:1094\n      [i] Disabled source: cms-xrd-transit.cern.ch:1094", 'exitCode': '8028'}], 'SiteHistory': ['Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC', 'Unknown', 'T2_TW_NCHC'], 'TotalSysCpuTimeHistory': [0, 0, 0]}}
INFO 2017-05-09 19:05:04,051: 	 Status on the scheduler:	FAILED
INFO 2017-05-09 19:05:04,051: 	 
Jobs status:                    failed        100.0% (11/11)
INFO 2017-05-09 19:05:04,051: 	 
No publication information (publication has been disabled in the CRAB configuration file)
INFO 2017-05-09 19:05:04,052: 	 
Error Summary: (use crab status --verboseErrors for details about the errors)

11 jobs failed with exit code 8028

Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.
INFO 2017-05-09 19:05:05,188: 	 Error: Cannot get all the needed information for the report. Notice, if your task has been submitted more than 30 days ago, then everything has been cleaned.
INFO 2017-05-09 19:05:05,198: 	 Log file is /afs/cern.ch/work/k/kjpena/CMSSW_8_0_8_patch1/src/test/macros/grid/crab_ZJ_ct14/crab.log
